### ISSUE TITLE
Add daily forecast (5 days)

### ISSUE THREAD

**Issue by mlecic** [mlecic/intern-weather-app#24]
As a user I want to search weather data by city name and see current weather data and also daily forecast (5 days).

Endpoint: api.openweathermap.org/data/2.5/forecast?lat=44.8&lon=20.4&appid=5637da4b8906e7d92ccc594c24b3a782

This endpoint should return 5 day / 3 hour forecast data. More info here https://openweathermap.org/forecast5.

DoD: add new component which will show 5 days forecast, displayed horizontally using CSS flexbox.

**Comment by lavstef** [comment]
Here is the API call:

api.openweathermap.org/data/2.5/forecast/daily?lat={lat}&lon={lon}&cnt={cnt}&appid=[{API key}](https://home.openweathermap.org/api_keys)

**Comment by lavstef** [comment]
Hi @mlecic , 

I believe we need another API key for mentioned API call above. Please review.

Thank you!

**Comment by mlecic** [comment]
@lavstef I've updated description, please find details for endpoint that works.

**Comment by lavstef** [comment]
Thank you!
